services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=student_crud
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
    volumes:
      - my-db:/var/lib/mysql

  api:
    container_name: express_api
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_PORT=3306
      - DB_HOST=mysql
    depends_on:
      - mysql
    volumes:
      - ./backend/src:/usr/src/api/src

volumes:
  my-db:

#docker compose up --build