services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3307:3306' #maps docker port to local port
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=blog_crud
    volumes:
      - my-db:/var/lib/mysql

  api:
    container_name: express_api
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - WAIT_HOSTS=mysql:3306
      - PORT=3000
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_NAME=blog_crud
      - DB_USER=root
      - DB_PASSWORD=pass123
    depends_on:
      - mysql
    volumes:
      - ./backend/src:/usr/src/api/src

volumes:
  my-db:

#docker compose up